site_name: FastAPI Interview Questions and Answers
site_url: https://mydomain.org/mysite
theme:
  name: material
  font:
    text: Avenir Regular
#    Avenir Regular
    code: Avenir Regular
#    Roboto Mono
